### ISSUE TITLE
Error on downloading

### ISSUE THREAD

**Issue by vlad00777** [roch1990/vk-photo-saver#1]
![cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/5796753/26215470/bb12fada-3c00-11e7-953b-d22968e6f860.png)

In log.txt
`2017-05-18 18:33:04,959 Error occured: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src\photodownloader.py", line 29, in photo_downloading
    photo = urllib.request.urlopen(self.PHOTO_DICT[key][item]).read()
TypeError: list indices must be integers or slices, not str
`

**Comment by roch1990** [comment]
@vlad00777 
https://github.com/roch1990/vk-photo-saver/commit/474311d13a50e7f7162189615d5b756d134cc81c

Fixed.

When you will tried this - please let me know. Thanks!

**Comment by roch1990** [comment]
@vlad00777 
I found some bugs else.
Please try this:
https://github.com/roch1990/vk-photo-saver/commit/e8e366321995dc7689c029c565709dbaff6e308a

It was tested at windows 7.

P.S: don't forget to install requests module. For example - from `requirements.txt`.

**Comment by roch1990** [comment]
Okay, I tested this issue at Ubuntu 16.04 and Windows 7. 
All was ok.

I close issue.
